version: '3.9'
services:

  app:
    build: .
    container_name: daniels-steaks-api
    ports:
      - 5000:5000
    volumes:
      - .:/home/node/app/daniels-steaks-api
    command: sh -c "npm install && bun dev"
    environment:
      - DB_ENGINE=
      - DB_SERVER=
      - DB_USER=
      - DB_PASSWORD=
      - DB_CLUSTER=
      - DATABASE=
      - ADMIN_KEY=
      - JWT_KEY=