version: '3.9'
services:

  app:
    build: .
    container_name: daniels-steaks-api
    ports:
      - 5050:5000
    volumes:
      - .:/home/node/daniels-steaks-api
    command: bun dev
    environment:
      - DB_ENGINE=
      - DB_SERVER=
      - DB_USER=
      - DB_PASSWORD=
      - DB_CLUSTER=
      - DATABASE=
    command: